// <auto-generated />
namespace ETAPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ModelAddedNotification : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModelAddedNotification));
        
        string IMigrationMetadata.Id
        {
            get { return "202002200732470_Model-Added-Notification"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
